# Site settings
title: kabochya.init();
email: pml0415@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Currently studying Electrical Engineering and Finance at National Taiwan University.
  Interested in integrating knowledge from different areas, trying to make our world a better place.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kabochya.github.io" # the base hostname & protocol for your site
twitter_username: kabochya
github_username:  kabochya
permalink: /:categories/:short_year-:month-:day/:title/
images: /assets/images
# Build settings
markdown: kramdown
